-- Create settings table
create table if not exists settings (
  id bigint generated by default as identity primary key,
  company_name text,
  cnpj text,
  address text,
  phone text,
  email text,
  theme text default 'light',
  stock_alerts boolean default true,
  auto_backup boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (optional but recommended, allowing all for now for simplicity in this dev env)
alter table settings enable row level security;

create policy "Enable all access for authenticated users" on settings
  for all using (true) with check (true);
